# .github/workflows/process-status-updates.yml
name: Process Weekly Status Updates

on:
  issues:
    types: [opened]

jobs:
  process-status-update:
    if: contains(github.event.issue.title, 'Weekly Status Update')
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Extract and process status data
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const issue = context.payload.issue;
          const issueBody = issue.body;
          
          // Extract JSON data from the comment
          const dataMatch = issueBody.match(/<!-- STATUS_UPDATE_DATA\n([\s\S]*?)\n-->/);
          if (!dataMatch) {
            console.log('No status update data found in issue');
            return;
          }
          
          let updates;
          try {
            updates = JSON.parse(dataMatch[1]);
          } catch (error) {
            console.log('Failed to parse status update data:', error);
            return;
          }
          
          console.log('Processing updates:', updates);
          
          // Process each update
          for (const update of updates) {
            const { issue_number, status, comment, user } = update;
            
            // Prepare the comment text
            let updateComment = `**Weekly Status Update by @${user}:**\n`;
            updateComment += `Status: ${getStatusEmoji(status)} ${status.replace('_', ' ')}\n`;
            
            if (comment) {
              updateComment += `\nComment: ${comment}`;
            }
            
            try {
              // Add comment to the target issue
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue_number,
                body: updateComment
              });
              
              // Update issue labels based on status
              const labelsToAdd = getLabelsForStatus(status);
              const labelsToRemove = ['status:in-progress', 'status:completed', 'status:blocked', 'status:needs-review'];
              
              // Get current labels
              const { data: currentIssue } = await github.rest.issues.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue_number
              });
              
              const currentLabels = currentIssue.labels.map(label => 
                typeof label === 'string' ? label : label.name
              );
              
              // Remove old status labels and add new ones
              const newLabels = currentLabels
                .filter(label => !labelsToRemove.includes(label))
                .concat(labelsToAdd);
              
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue_number,
                labels: newLabels
              });
              
              // Close issue if completed
              if (status === 'completed') {
                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue_number,
                  state: 'closed'
                });
              }
              
              console.log(`Updated issue #${issue_number}`);
              
            } catch (error) {
              console.log(`Failed to update issue #${issue_number}:`, error);
            }
          }
          
          // Close the status update issue
          await github.rest.issues.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issue.number,
            state: 'closed'
          });
          
          // Add a summary comment
          const summaryComment = `âœ… Status updates processed successfully!\n\n` +
            `Updated ${updates.length} issue(s):\n` +
            updates.map(u => `- #${u.issue_number}: ${getStatusEmoji(u.status)} ${u.status.replace('_', ' ')}`).join('\n');
          
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issue.number,
            body: summaryComment
          });
          
          function getStatusEmoji(status) {
            const emojis = {
              'in_progress': 'ðŸ”„',
              'completed': 'âœ…',
              'blocked': 'ðŸš«',
              'needs_review': 'ðŸ‘€'
            };
            return emojis[status] || 'ðŸ“';
          }
          
          function getLabelsForStatus(status) {
            const labelMap = {
              'in_progress': ['status:in-progress'],
              'completed': ['status:completed'],
              'blocked': ['status:blocked'],
              'needs_review': ['status:needs-review']
            };
            return labelMap[status] || [];
          }

---

# .github/workflows/generate-weekly-form.yml (Optional)
name: Generate Weekly Status Form

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual trigger

jobs:
  generate-form:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Generate weekly reminder issue
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const today = new Date().toISOString().split('T')[0];
          
          // Get all open issues assigned to team members
          const { data: issues } = await github.rest.issues.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'open',
            assignee: '*', // Get issues with any assignee
            per_page: 100
          });
          
          // Group issues by assignee
          const issuesByAssignee = {};
          issues.forEach(issue => {
            if (issue.assignees && issue.assignees.length > 0) {
              issue.assignees.forEach(assignee => {
                if (!issuesByAssignee[assignee.login]) {
                  issuesByAssignee[assignee.login] = [];
                }
                issuesByAssignee[assignee.login].push(issue);
              });
            }
          });
          
          // Create reminder issue
          const assignees = Object.keys(issuesByAssignee);
          if (assignees.length === 0) {
            console.log('No assigned issues found');
            return;
          }
          
          let reminderBody = `# ðŸ“‹ Weekly Status Update Reminder - ${today}\n\n`;
          reminderBody += `Hi team! Time for your weekly status update.\n\n`;
          reminderBody += `## How to submit your update:\n`;
          reminderBody += `1. Visit the [status update form](https://your-username.github.io/your-repo)\n`;
          reminderBody += `2. Fill out the status for each of your assigned issues\n`;
          reminderBody += `3. Submit the form to automatically update the issues\n\n`;
          reminderBody += `## Current assigned issues:\n\n`;
          
          for (const [assignee, userIssues] of Object.entries(issuesByAssignee)) {
            reminderBody += `### @${assignee} (${userIssues.length} issues)\n`;
            userIssues.forEach(issue => {
              reminderBody += `- #${issue.number}: ${issue.title}\n`;
            });
            reminderBody += `\n`;
          }
          
          reminderBody += `---\n`;
          reminderBody += `*This is an automated reminder. Please submit your status update by end of day.*`;
          
          await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `ðŸ“‹ Weekly Status Update Reminder - ${today}`,
            body: reminderBody,
            assignees: assignees,
            labels: ['reminder', 'status-update']
          });
          
          console.log(`Created reminder issue for ${assignees.length} team members`);

---

# .github/workflows/deploy-form.yml (Optional - for GitHub Pages deployment)
name: Deploy Status Form to GitHub Pages

on:
  push:
    branches: [ main ]
    paths: [ 'status-form.html' ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3